### PR TITLE
fix for special characters in filenames

### PR DESCRIPTION
**Pull request by HendrikRoth**
fix for #7, #4

### CODE REVIEW

**Comment by Jnesselr** [comment]
Regex. Nice. I don't think this actually fixes #4 though. It might, but I don't think it'd fix [this](https://github.com/Jnesselr/fusion-360-total-exporter/issues/4#issuecomment-695079385) comment. I'm going to accept it anyway.

**Comment by HendrikRoth** [comment]
i think so, because we are now replacing even the `:` character.

**Comment by Jnesselr** [comment]
> i think so, because we are now replacing even the `:` character.

Ah, I don't believe the colon and the number after the colon are included in the name itself. Might be a useful thing to test explicitly.

**Comment by Gnindit** [comment]
> > i think so, because we are now replacing even the `:` character.
> 
> Ah, I don't believe the colon and the number after the colon are included in the name itself. Might be a useful thing to test explicitly.

I agree, colon and the number after is not included in the name.

If I get a script that only runs the design I have open I could test a little.

**Pull request merged**
